### ISSUE TITLE
Recreate project

### ISSUE THREAD

**Issue by janhohenheim** [MarcusSakae/refactored-octo-tribble#1]
Hi! I've noticed that people that used Foxtrot as a _template_ instead of _forking_ it had issues with the LFS assets, so i put them into git now. This means you'll have a working repo if delete this repo and recreate it by clicking on [use this template](https://github.com/janhohenheim/foxtrot/generate).
Have fun! :)

**Comment by MarcusSakae** [comment]
I actually ran into that problem immediately after using the template, so I just cloned the repo instead and force-pushed it here . (so the code in this repo is actually not generated from the template, even if it may seem that way at first glance).  But thanks! =)

**Comment by janhohenheim** [comment]
Glad to hear! 😄
